# Generated by Django 5.0.3 on 2024-03-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookno', models.IntegerField(primary_key='bookno', serialize=False)),
                ('bookname', models.CharField(max_length=20)),
                ('authorname', models.CharField(max_length=40)),
                ('publishdate', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
